"""Update Habit table

Revision ID: 17c042e33bb6
Revises: e6920861d6ba
Create Date: 2025-03-28 12:13:49.873656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c042e33bb6'
down_revision: Union[str, None] = 'e6920861d6ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit', sa.Column('current_streak', sa.Integer(), nullable=True))
    op.add_column('habit', sa.Column('max_streak', sa.Integer(), nullable=True))
    op.add_column('habit', sa.Column('last_completed_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit', 'last_completed_date')
    op.drop_column('habit', 'max_streak')
    op.drop_column('habit', 'current_streak')
    # ### end Alembic commands ###
