"""Streak table max and current streak default updated to zero

Revision ID: 76687ca20869
Revises: 35b3847134f1
Create Date: 2025-03-28 12:52:39.345096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76687ca20869'
down_revision: Union[str, None] = '35b3847134f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habit', 'current_streak',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('habit', 'max_streak',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habit', 'max_streak',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('habit', 'current_streak',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
